---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp
  namespace: 12-example
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::005654795190:role/staging-weather-app-eks-cluster-myapp-secrets